#! configuration/base.yml
application:
  port: 8000
  host: 127.0.0.1
database:
  host: "127.0.0.1"
  port: 5432
  username: "postgres"
  password: "password"
  database_name: "newsletter"


email_client:
  base_url: "https://api.postmarkapp.com"
  sender_email: "mail@dennohpeter.com"
  authorization_token: "3bc125f1-0380-42b8-aa5d-57112396b09f"